name: hello
on: push
jobs:
  hello:
    name: hello
    runs-on: ubuntu-latest
    container:
      image: openjdk:8-jdk

    steps:
      - name: Hello
        run: |
          echo "hello"
          java -version
