name: hello
on: push
jobs:
  hello:
    name: hello
#     runs-on: ubuntu-latest
    runs-on: windows-2019
    defaults:
      run:
        shell: bash

    steps:
      - name: Hello
        run: |
          pwd
          ls -la
          cd ~
          pwd
          ls -la
          echo "hi"
          echo "hello"
