name: hello
on: push
jobs:
  hello:
    name: hello
    runs-on: ubuntu-latest
    container:
      image: openjdk:8-jdk

    steps:
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 8

    - name: Hello
      run: |
        echo "hello"
        java -version
