name: hello
on: push
jobs:
  hello:
    name: hello
    defaults:
      run:
        working-directory: "~/repo"
    runs-on: ubuntu-latest
    container:
      image: openjdk:8-jdk

    steps:
      - name: Hello
        run: |

          echo "hello"
          pwd
          ls -la
          java -version
